name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish --configuration Release

    - name: Create zip file
      run: zip -r XmagNews.zip ./bin/Release/net8.0/

    - name: GH Release
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: XmagNews.zip
        body_path: CHANGELOG

